# Generated by Django 4.0.1 on 2022-01-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_rename_company_payer_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
