# Generated by Django 4.0.1 on 2022-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_payer_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
