# Generated by Django 4.0.1 on 2022-01-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_payer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spent',
            field=models.BooleanField(default=False),
        ),
    ]
